keys:
  - &pan age1ppauct9zunahsvlfaut3dxd5r2nq09zppknv3fcghx4hdll26uaqfvlz3n
  - &zeus ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDXQcojTiuyFuYWsHQ4Cd9mZcBzPY3nxbllyNW6SuW7
  - &ares age17x2zeaw8culu9ug6rgs56ghf46rkj9574tpfj3xjzs2yy26u5fts25a6r4

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *pan
          - *zeus
          - *ares
