name: "Update, Build and Cache"

on:
  workflow_dispatch:
    inputs:
      update:
        description: "Update flake.lock before building"
        required: true
        default: false
        type: boolean
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: push-and-pray-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Update flake.lock
        id: update
        if: github.event_name == 'schedule' || inputs.update
        run: |
          nix flake update --accept-flake-config

          if git diff --quiet -- flake.lock; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check flake
        if: github.event_name == 'workflow_dispatch' || steps.update.outputs.changed == 'true'
        run: nix flake check --accept-flake-config

      - name: Build Host
        if: github.event_name == 'workflow_dispatch' || steps.update.outputs.changed == 'true'
        run: |
          nix build \
            .#nixosConfigurations.zeus.config.system.build.toplevel \
            .#nixosConfigurations.ares.config.system.build.toplevel \
            .#nixosConfigurations.hermes.config.system.build.toplevel \
            .#nixosConfigurations.pan.config.system.build.toplevel \
            --accept-flake-config

      - name: Commit flake.lock
        if: steps.update.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "chore: update flake.lock"
          git push
